### ISSUE TITLE
modular accelerators and thruster stops working after a while.

### ISSUE THREAD

**Issue by firespark81** [Esteemed-Innovation/Esteemed-Innovation#175] opened 2015-01-01 07:17 UTC
Playing Resonant Rise mod pack with most mods installed. Made a suit have it full of steam. Everything works fine and the modular accelerator worked when I first installed it but then it stopped. My move speed is the same as walking. Not sure what causes it yet, but I will try my best to track down the issue. Just wanted to make you aware. If you would like any more info that I have neglected to include please let me know.

**Comment by 4rz0** [comment] 2015-01-07 20:51
I have the same problem.
Happens with Thrusters and the Modular Accelerator for me.
It usually happens after I've been logged out for a while and log back in.
A server-restart "fixes" this problem.

**Comment by allaryin** [comment] 2015-01-07 21:38
Re 4zr0's issue, the server does not log any errors. There is no indication as to when precisely things stop functioning for him.

**Comment by UkeFox** [comment] 2015-05-30 08:02
I know this is old, but it's still open. Just started having this issue too. I'm running Tolkiencraft II and just like Firespark, Modular Accelerator was working great then it wasn't. I've tried making a whole new suit new modules and a few other things here and there. Also a server restart didn't resolve the issue. I'm not seeing any errors in the server logs so I'm stumped.

**Comment by xbony2** [comment] 2015-05-30 11:39
Aye.

**Comment by elifoster** [comment] 2015-11-11 04:49
This needs to be fixed. Pushed to 0.29.0 milestone.

**Comment by elifoster** [comment] 2015-11-14 15:37
I'm unable to reproduce this issue. I've been running around my test world for a few minutes and nothing is happening. Is it completely random or is there something specifically that is done before it happens?

@firespark81 @UkeFox @allaryin @4rz0 @xbony2

**Comment by 4rz0** [comment] 2015-11-14 17:16
Sometimes, it took hours until this problem appeared, and disappeared after a server restart, sometimes, it reappeared after a few minutes and didn't go away.

**Comment by elifoster** [comment] 2015-11-14 17:17
Does it happen only when on a server?
Does it happen when only Flaxbeard's Steam Power is installed, or are other mods always installed?

**Comment by 4rz0** [comment] 2015-11-14 18:32
I only play on servers, so I don't know if it happens in singleplayer.
We only tried it with other mods installed, but I will put up a server with only Steam Power installed to give it a try.

**Comment by elifoster** [comment] 2015-11-14 18:56
Thanks.
Could you provide your mod list so that I can see if any of the mods may have some compatibility issues?

**Comment by 4rz0** [comment] 2015-11-17 09:20
The modlist is here: http://files.mcupdater.com/crystal_elephant/ServerPack.xml
It's outdated, we haven't played that server in quite a while.
It was pretty much up to date when I commented on that issue.

**Comment by elifoster** [comment] 2015-11-25 08:01
The only mod I can see that might be causing this is Galacticraft, as IIRC it replaces the EntityPlayer and that has caused a lot of issues in the past with other mods. Not sure if they still do that.

If some of you other guys (@firespark81 @UkeFox @allaryin) could provide your mod lists so that I can actually compare them, that would be awesome. I will also ask the person who reported this on the MCF thread.

**Comment by elifoster** [comment] 2015-11-30 08:41
If no one is able to provide a second mod list, this bug is probably not going to be fixed by 0.29, unfortunately. Just a fair warning.

**Comment by 4rz0** [comment] 2015-11-30 09:11
The one I mentioned is also allaryin's.
I'm currently experimenting with 2 packs that include both the recommended versions of Steampower and Galacticraft on lastest forge for 1.7.10.

**Comment by elifoster** [comment] 2015-11-30 09:13
I need two separate mod lists to see similarities, though. If you can personally reproduce the issue in both of those packs, then provide me with both mod lists, that would be super awesome.

**Comment by 4rz0** [comment] 2015-11-30 10:25
Ok, first results say it's mod-interaction between Steampower and Galacticraft.
I tried that in a minimum pack with only Steampower and Galacticraft (and NEI, of course) installed, the Modular Accelerator doesn't work from the start, with Galacticraft disabled, it does work.

However, I'm not quite sure about that, since I can not measure how fast I am, I just can say what it "feels" like.
Is there any way to actually measure the current player speed?

If it really is a mod-interaction problem, the actual difficult part would be to find out what exactly fails, is there a way I can help with that?

**Comment by elifoster** [comment] 2015-11-30 17:32
The upgrade is so much faster than normal walking, so you should be able to just tell.

Right now, I'm unsure about other ways you can help.

**Comment by elifoster** [comment] 2015-11-30 18:05
@4rz0 Could you perhaps test it in a pack without GC? I'm unable to reproduce it in my test instance, but it seems like you have better luck with that.

**Comment by 4rz0** [comment] 2015-11-30 23:13
Thanks to @squeek502 and his Speedometer-HUD mod, I can test this for sure now.
However, that's where the problems start.
I can not, in fact, reliably reproduce the problem yet. Even without Galacticraft installed, both the Modular Accelerator and the Thrusters are broken.

I'll keep trying and experimenting with things I had in the modpacks I was experimenting with...

**Comment by 4rz0** [comment] 2015-12-01 00:03
And now for the bad news:
The behaviour occurs at random, with every restart of the client (since I tried with SSP, not sure what happens with SMP, but I suppose it's the server in that case, I'll try that later.).
I tried that with just Steam Power (and a few utility mods) installed.

I'll link some logs, although they seem to be pretty useless, I ran them trough a differ and there's nothing of interest in there.
https://www.dropbox.com/sh/5z21qmc8ayu8sw0/AACcALUDT63rLXghQ7a05Exna?dl=0
In the first three, I relogged the map multiple times to see if behaviour is constant without client restarts, which it is.
The rest, I startet a map ran around and quit.

**Comment by elifoster** [comment] 2015-12-01 00:11
The only thing I can think of that would be causing this is the usage of Entity IDs, but I don't really know much about those. I'll do some research and find out what they do. I think something more unique would probably fix this issue, but I am not certain.

**Comment by elifoster** [comment] 2015-12-01 00:17
Looking at the Event Handler code, if the usage of getEntityId was the problem, we'd see this issue with a bunch of other upgrades, which we don't.

**Comment by elifoster** [comment] 2015-12-01 04:34
My god. I just reproduced this. Unfortunately this was in the ieep branch, so it is not the getEntityId thing that is the problem.

**Comment by 4rz0** [comment] 2015-12-01 11:10
Another interesting find:
The chance for those features to fail exclusively depend on the client.
I experimented with a SMP environment, but restarting the server didn't change if the features worked or not, this only really happens when restarting the client.

**Comment by elifoster** [comment] 2015-12-30 02:45
That makes me wonder whether we are modifying the NBT for these items on the client. I'll investigate a little bit.

**Comment by 4rz0** [comment] 2015-12-30 09:29
:(

**Comment by elifoster** [comment] 2016-01-08 03:34
Removing this from the 0.29 milestone because I want to get that pushed ASAP, and this has so far proven to be unpredictable and complicated, which takes a lot of time. If we can continue figuring out how to deal with it, that would be awesome.

**Comment by 4rz0** [comment] 2016-01-08 08:39
I'm always here to help with that :D

**Comment by 4rz0** [comment] 2016-03-18 08:55
Any new changes made for this to be tested?

**Comment by elifoster** [comment] 2016-03-18 16:52
Nope 😢

**Comment by elifoster** [comment] 2017-03-25 22:10
According to OutcastZeroOne, with the latest alpha build, this does not seem to be an issue anymore. If someone gets it again with 1.0.0+, feel free to reopen it.

**Closed by elifoster** 2017-03-25 22:10 UTC
Labels: Content: Exosuit, Priority: Medium, Status: Unconfirmed, Type: Bug
