### ISSUE TITLE
several blocks don't function correctly after having their chunks reloaded

### ISSUE THREAD

**Issue by Rosethorns** [Esteemed-Innovation/Esteemed-Innovation#186] opened 2015-01-16 00:15 UTC
seems to be sporadic but the flash boiler will sometimes appear to be completely empty of steam and water and you will not be able to interact with it (feed fuel/water) until you break and replace a block to reinitialize it.

Vacuums will not suck up items until they are broken and replaced in a similar way to the above.

Valve pipes that /were/ closed, will now be open but still graphically show as closed. fixing these requires that you open and then close the valve again. 

All three of these issues are related to chunk saving/loading that contain Flaxbeard's tile entities
makes using Flaxbeard's reliably extremely frustrating.

**Comment by Gholuk** [comment] 2015-01-28 21:52
@Valve Pipes: I tried something to fix this.
This issue should be made to three issues as these issues are not related in anyway from what I see.

**Comment by Rosethorns** [comment] 2015-01-29 06:51
@Gholuk they are all related because they all have the same cause, not keeping their state on chunk reload.

**Comment by Ghoughpteighbteau** [comment] 2015-01-29 18:32
@Rosethorns I couldn't reproduce that. loading and unloading the game works fine for the vacuum as near as I can tell, as well as loading and unloading chunks. However I found a range of other issues with it that definitely lined up with what you were saying. 

The flash boiler does loose steam and water occasionally, but it seems to be a re-formation bug. The multiblock structures need to be reviewed.

I could not reproduce the issue with valves, again they survived the loading/unloading with their settings... though reviewing the code, they are very strange blocks... I don't doubt there be dragons.

The only device that seems to have issues with chunk loading/unloading is the flash boiler. The other two have their own. 

At least in my own estimation.

Can you provide some steps to reproduce the issues in a test world?

**Comment by AcidDotCom** [comment] 2015-03-10 20:21
I have this issue in my world all the time. It happens when I'm restarting the game. All the steam is going out and opening and closing the valves help. I'm not sure will it fail in the same way when I'm reloading the chunks (i.e. travelling), as I've just started using this mod properly few days ago.
Never had an issue of other blocks not working though.

**Comment by Gholuk** [comment] 2015-03-12 19:57
@AcidDotCom: What version do you use? You are describing an issue that was fixed in 0.27.4...

**Comment by AcidDotCom** [comment] 2015-03-12 22:14
I'm using the Blast Off 1.3.0 modpack....just noticed that the 0.27.2 is included in that pack. Glad to know that it have been fixed :)

**Comment by elifoster** [comment] 2015-03-12 22:16
@AcidDotCom You should tell the author of that to update once the next version comes out.

**Comment by AcidDotCom** [comment] 2015-03-12 22:33
Already did :)
No other issues found...so far, so great job on the mod :D

**Comment by elifoster** [comment] 2015-12-27 22:16
So is the only remaining bug described here for the flash boiler? Can someone correct me or describe that bug in better detail?

**Comment by Divineaspect** [comment] 2016-01-04 20:03
I can't reproduce this, but I'll save a world to keep testing against in case it comes up again.

**Comment by elifoster** [comment] 2017-03-24 17:26
If the only issue remaining is related to the flash boiler, this can be closed, as that is removed in 1.0.0. @DivineAspect ?

**Comment by Divineaspect** [comment] 2017-03-24 17:59
makes sense to me, I'll just test for this specific thing going forward.

**Closed** 2017-03-24 18:27 UTC
Labels: Content: SteamNet and Technology, Priority: High, Status: Cannot Reproduce, Type: Bug
