### ISSUE TITLE
Unable to start world, kicked back to main menu with Mekanism error

### ISSUE THREAD

**Issue by DeusExNihil** [Esteemed-Innovation/Esteemed-Innovation#298] opened 2015-08-10 17:47 UTC
http://pastebin.com/1cyBStqx

I began getting this error after adding a batch of mods to my modpack. Removing Steam Power fixed said error. I'm not an expert by any means, so I've no idea what is causing this, other than a conflict with Mekanism.

**Comment by elifoster** [comment] 2015-08-10 17:58
Have you reported this to the Mekanism developers?

**Comment by DeusExNihil** [comment] 2015-08-10 19:58
Yes, although at the time I did not know for sure it was caused by this mod. I'm going to update the post now

**Comment by elifoster** [comment] 2015-08-11 18:37
It still isn't confirmed that we are causing the issues.

**Comment by hlaaftana** [comment] 2015-08-30 18:27
https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/recipe/inputs/MachineInput.java#L32
Most likely Mekanism issue.

**Comment by Tsyklop** [comment] 2015-09-05 09:32
I recreate the configuration file FSP and everything was fine.

**Comment by hlaaftana** [comment] 2015-09-05 11:39
close close close close

**Comment by elifoster** [comment] 2015-09-05 18:29
Why was this closed? The bug isn't fixed, and we don't know for sure that it's mekanisms fault

**Comment by hlaaftana** [comment] 2015-09-05 18:31
It isn't confirmed, and he said removing the config fixed it...
He probably messed up something in the configs.

**Comment by elifoster** [comment] 2015-09-05 23:21
Removing what from the configs?...

**Comment by Tsyklop** [comment] 2015-09-06 04:19
@elifoster Removed config file FSP, and everything was fine.

**Comment by elifoster** [comment] 2015-09-06 18:12
Can you paste the old config file?

**Comment by Tsyklop** [comment] 2015-09-06 18:17
@elifoster http://pastebin.com/caapRiXz

**Comment by elifoster** [comment] 2015-09-06 20:50
I don't see anything wrong with it, but if all it was was a bad config, closing.

**Closed as completed by elifoster** 2015-09-06 20:50 UTC
Labels: Type: Bug, Status: Invalid, Crossmod, Configuration

**Comment by Tsyklop** [comment] 2015-09-11 13:06
I found out because of that crash ...
If the config change everything value at false it will crash.

    B:"Enable Copper Ore. This does not enable world generation of the ore, but will disable it if false."=true
    B:"Enable Poor Zinc Ore. This does not enable world generation of the ore, but will disable it if false."=true
    B:"Enable Zinc Ore. This does not enable world generation of the ore, but will disable it if false."=true

**Comment by hlaaftana** [comment] 2015-09-11 13:56
Don't get what you mean. If you type in anything other than "true" or "false" in there, it will not work.

**Comment by elifoster** [comment] 2015-12-31 06:03
@hlaaftana For what it's worth, despite this being a completely dead issue, that's actually not true. Look at Boolean#parseBoolean; it checks if it is "true" with any casing, and not null. Otherwise it assumes false.
